import Navbar from "@/Components/Navbar";
import "./globals.css";
import {Archivo, Inter} from "next/font/google"

const brandFont = Inter({preload : false}) 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={brandFont.className}>
        <div className="sticky top-10">
        <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
